### PR TITLE
Firebase Setup

### PR DESCRIPTION
**Pull request by nicoleamaral37**
Added dependencies and linked app to firebase

[Link ](https://rnfirebase.io/)to check work

### CODE REVIEW

**Review by luciuskarki — DISMISSED** [review]
Solid

**Comment by nicoleamaral37** [comment]
.idea comes from android studio

**Review by Solarific — APPROVED** [review]

**Review by Solarific — COMMENTED** [review]
not sure why vector images are missing? ran *npm install react-native-firebase" , 
image

any idea?

**Review by Solarific — COMMENTED** [review]
So after getting the build running, I clicked on login just for fun, and crashed due to missing dependencies.

npm install --save @react-native-firebase/app

**Task :react-native-firebase:compileDebugJavaWithJavac FAILED**
npm install @react-native-firebase/app @react-native-firebase/firestore
npx jetify

solved these issues, followed by this next error I cannot solve
**Task :app:mergeLibDexDebug FAILED**

Did any of these errors occur when you were building? 

UPDATE - I have deleted react-native-firebase from node modules for now, if you have documentation for the correct dependency installs, please let me know!

**Comment by nicoleamaral37** [comment]
> So after getting the build running, I clicked on login just for fun, and crashed due to missing dependencies.
> 
> 
> 
> npm install --save @react-native-firebase/app
> 
> 
> 
> **Task :react-native-firebase:compileDebugJavaWithJavac FAILED**
> 
> npm install @react-native-firebase/app @react-native-firebase/firestore
> 
> npx jetify
> 
> 
> 
> solved these issues, followed by this next error I cannot solve
> 
> **Task :app:mergeLibDexDebug FAILED**
> 
> 
> 
> Did any of these errors occur when you were building? 
> 
> 
> 
> UPDATE - I have deleted react-native-firebase from node modules for now, if you have documentation for the correct dependency installs, please let me know!
> 
> 

try this 
yarn add @react-native-firebase/auth

**Review by Solarific — APPROVED** [review]
Working as intended!

**Review by luciuskarki — APPROVED** [review]
Works after installing font dependency, nice stuff

**Pull request merged**
