### PR TITLE
Map

### PR DESCRIPTION
**Pull request by just-an-e**
The google map works on the front page now

### CODE REVIEW

**Comment by luciuskarki** [comment]
Would you be able to fix the merge conflicts that this branch has?

**Comment by just-an-e** [comment]
Yeah I'm going to fix them tonight

**Comment by just-an-e** [comment]
Merge conflicts resolved

**Comment by nicoleamaral37** [comment]
I'm having trouble running it. I tried npm i react-native-maps but didn't resolve my issue, any ideas?

image

**Pull request closed without merging**
